name: Kubernetes-deployment

on:
  workflow_run:
    workflows: [build and push docker image]
    types:
      - completed

jobs:
 deploy:
 name: deploy-to-kubernetes
 runs-on: kubernetes-runner
 steps:
 – shell: bash
 run: |
 kubectl apply -f https://raw.githubusercontent.com/siddhant-khisty/key-store-gin/main/Kubernetes/deply.yaml
 kubectl apply -f https://raw.githubusercontent.com/siddhant-khisty/key-store-gin/main/Kubernetes/ingress.yaml
 kubectl apply -f https://github.com/siddhant-khisty/key-store-gin/blob/main/Kubernetes/svc.yaml
